### ISSUE TITLE
How to Display the Midi Channel

### ISSUE THREAD

**Issue by derGraph** [bneedhamia/midifilestream#4]
Is it possible to get the channel of the note?
Thanks Paul

**Comment by bneedhamia** [comment]
I haven't tested channel information, but there is code in the library to return the channel number for every Channel event. As you probably already know, MidiDump.ino in this respository is an example of reading a Midi file using this library. Although MidiDump.ino doesn't print channel numbers, it does have code for reading everything else in the channel event.

As a result of your question I've added an Enhancement issue to the repo to remind me to add code to MidiDump.ino to print the channel number.

Line 188 in MidiDump.ino gets one field common to all channel messages: the channnel event code:
`char code = midiFile.getEventDataP()->channel.code;`
To get the Midi Channel number from the channel event, do something like this:
`int channel = midiFile.getEventDataP()->channel.chan; // Midi channel number, 0..15`

As you may know, a Midi stream doesn't provide the channel number for every channel event. It uses something called "running status" to send fewer byes. For this reason, the midifilestream library maintains the running status for you so your application doesn't have to remember the channel number between events. Every ET_CHANNEL event returned by the library has a valid channel.chan field.

Please add a Comment on this Issue to let me know whether this is enough information for you, or whether you need more help. I'm delighted you're using the library!

Good luck, and let me know how it goes.

**Comment by bneedhamia** [comment]
The TL;DR version of the previous comment: To get the Midi Channel number from the channel event, do something like this:
`int channel = midiFile.getEventDataP()->channel.chan; // Midi channel number, 0..15`

**Comment by derGraph** [comment]
It doesn't work for me, when I run it the channel seems pretty weird: I get outputs that are not true
20:45:02.099 -> Calling SD.begin()...
20:45:02.099 -> ...succeeded.
20:45:02.134 -> Midi file format: 1
20:45:02.134 -> Number of tracks: 14
20:45:02.134 -> Ticks per beat: 192
20:45:02.134 -> delay 0 ticks.
20:45:02.134 -> New Tempo: 769230 microseconds per beat.
20:45:02.134 -> delay 0 ticks.
20:45:02.134 -> delay 56832 ticks.
20:45:02.134 -> New Tempo: 389610 microseconds per beat.
20:45:02.134 -> delay 21888 ticks.
20:45:02.134 -> New Tempo: 769230 microseconds per beat.
20:45:02.134 -> delay 183423 ticks.
20:45:02.134 -> End of Track event.
20:45:02.134 -> delay 0 ticks.
20:45:02.168 -> delay 170 ticks.
20:45:02.168 -> delay 72 ticks.
20:45:02.168 -> delay 2 ticks.
20:45:02.168 -> delay 2 ticks.
20:45:02.168 -> delay 2 ticks.
20:45:02.168 -> delay 0 ticks.
20:45:02.168 -> delay 0 ticks.
20:45:02.168 -> delay 2 ticks.
20:45:02.168 -> delay 0 ticks.
20:45:02.168 -> delay 12806 ticks.
20:45:02.168 -> Note On: Midi channel 5 72
20:45:02.168 -> delay 0 ticks.
20:45:02.168 -> Note On: Midi channel 5 74
20:45:02.168 -> delay 22 ticks.
20:45:02.168 -> Note Off: Midi channel 5 72
20:45:02.168 -> delay 638 ticks.
20:45:02.168 -> Note Off: Midi channel 5 74
In my music software it displays as channel 5 when the start meldody is on channel 4
![image](https://user-images.githubusercontent.com/68235499/100387793-3a030180-3029-11eb-86b8-bc166dffabe9.png)

**Comment by bneedhamia** [comment]
I forgot to mention: the library (and Midi binary codes) represents the channel number as 0..15, not 1..16. So channel 1 is represented by a .chan value of 0, channel 2 by .chan value of 1, etc. So The music software talking about channel 5 is the same as a .chan value of 4.

So if you want your application to print channel numbers that match your music software, do something like:
`int channel = 1 + midiFile.getEventDataP()->channel.chan; // Midi channel number, 1..16`

**Comment by derGraph** [comment]
Thanks, I will try this

**Comment by Akrobate** [comment]
Hello, the channel param works perfectly
1 + midiFile.getEventDataP()->channel.chan
